# Generated by Django 4.2.7 on 2026-01-15 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('screen', '数据可视化大屏'), ('report', '中国式复杂报表')], max_length=20, verbose_name='项目类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='projects_type_c05cb7_idx'), models.Index(fields=['status'], name='projects_status_6303d7_idx'), models.Index(fields=['created_by'], name='projects_created_428cb1_idx')],
            },
        ),
    ]
