# Generated by Django 4.2.7 on 2026-01-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='角色描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统内置')),
                ('scope', models.CharField(choices=[('all', '全部数据'), ('dept', '本部门'), ('self', '仅本人'), ('custom', '自定义')], default='self', max_length=20, verbose_name='数据权限范围')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='roles_name_a96913_idx'), models.Index(fields=['is_system'], name='roles_is_syst_8ea1ed_idx')],
            },
        ),
    ]
